# Generated by Django 6.0.1 on 2026-02-07 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_qform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='qForm',
        ),
    ]
